/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personality;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author MOHIT
 */
public class comment_1 extends javax.swing.JFrame {

    /**
     * Creates new form comment
     */
    public comment_1() {
        initComponents();
        setBounds(450, 180, 350, 400);
        getContentPane().setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 180, 350, 400));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Your Roll No.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 100, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Roll No.");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 49, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setText("Characteristics:--");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 130, 114, 18);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 60, 140, 23);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 90, 140, 23);

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox1.setText("Confident");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(30, 150, 120, 25);

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox2.setText("Quick Learner");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(30, 180, 120, 25);

        jCheckBox3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox3.setText("Talented");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(30, 210, 120, 25);

        jCheckBox4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox4.setText("Punctual");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(30, 240, 120, 25);

        jCheckBox5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox5.setText("Helpfull");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(30, 270, 120, 25);

        jCheckBox6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox6.setText("Hardwork");
        getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(30, 300, 120, 25);

        jCheckBox7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox7.setText("Short-Tempered");
        getContentPane().add(jCheckBox7);
        jCheckBox7.setBounds(200, 150, 119, 25);

        jCheckBox8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox8.setText("Irresponsible");
        getContentPane().add(jCheckBox8);
        jCheckBox8.setBounds(200, 180, 99, 25);

        jCheckBox9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox9.setText("Mysterious");
        getContentPane().add(jCheckBox9);
        jCheckBox9.setBounds(200, 210, 89, 25);

        jCheckBox10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox10.setText("Judgemental");
        getContentPane().add(jCheckBox10);
        jCheckBox10.setBounds(200, 240, 95, 25);

        jCheckBox11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox11.setText("Self-centered");
        getContentPane().add(jCheckBox11);
        jCheckBox11.setBounds(200, 270, 101, 25);

        jCheckBox12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox12.setText("Lazy");
        getContentPane().add(jCheckBox12);
        jCheckBox12.setBounds(200, 300, 53, 25);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 340, 85, 25);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 10, 65, 25);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 10, 71, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("(Person to be commented on)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 140, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/per?autoconnect=true&useSSl=false","root","");
            Statement stmt=con.createStatement();
            long roll=Long.parseLong(jTextField1.getText());
            long roll1=Long.parseLong(jTextField2.getText());
            long sd=0,rd=0;
            int pt=0;
            if(roll!=roll1){
            ResultSet rs=stmt.executeQuery("SELECT * FROM main WHERE roll='"+roll+"'");
            while(rs.next()){
                sd=Long.parseLong(rs.getString("aadhar"));
                System.out.println(sd);
            }
            ResultSet rs1=stmt.executeQuery("SELECT * FROM main WHERE roll='"+roll1+"'");
            while(rs1.next()){
                rd=Long.parseLong(rs1.getString("aadhar"));
                System.out.println(rd);
            }
            if(sd!=0 && rd!=0){
            if(jCheckBox1.isSelected()){
                pt+=20;
            }
            if(jCheckBox2.isSelected()){
                pt+=20;
            }
            if(jCheckBox3.isSelected()){
                pt+=20;
            }
            if(jCheckBox4.isSelected()){
                pt+=20;
            }
            if(jCheckBox5.isSelected()){
                pt+=20;
            }
            if(jCheckBox6.isSelected()){
                pt+=20;
            }
            if(jCheckBox7.isSelected()){
                pt-=20;
            }
            if(jCheckBox8.isSelected()){
                pt-=20;
            }
            if(jCheckBox9.isSelected()){
                pt-=20;
            }
            if(jCheckBox10.isSelected()){
                pt-=20;
            }
            if(jCheckBox11.isSelected()){
                pt-=20;
            }
            if(jCheckBox12.isSelected()){
                pt-=20;
            }
            double t=0.0,p=0.0;
            String s="";
            String sql="INSERT INTO comment (saadhar, raadhar, points)VALUES ('"+sd+"', '"+rd+"','"+pt+"')";
            stmt.executeUpdate(sql);
            ResultSet rs2=stmt.executeQuery("SELECT * FROM main WHERE roll='"+roll1+"'");
            while(rs2.next()){
                t=Double.parseDouble(rs2.getString("total"));
                p=Double.parseDouble(rs2.getString("points"));
                s=rs2.getString("email");
            }
            t+=1;
            if(pt>0){
                p+=1;
            }
            if(pt==0){
                p+=0.5;
            }
            stmt.executeUpdate("UPDATE main SET total='"+t+"' WHERE roll='"+roll1+"'");
            stmt.executeUpdate("UPDATE main SET points='"+p+"' WHERE roll='"+roll1+"'");
             System.out.println("updated");
              System.out.println("Sending Mail....");
              
        SendMail obj=new SendMail();
        obj.send(s,"New Comment","Someone has added a new comment. Now your scores are "+p+"/"+t+". Thank You!","npp95239@gmail.com","17309521913");     
           
            jTextField1.setText("");
        jTextField2.setText("");
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        jCheckBox12.setSelected(false);
            }
            else{
                System.out.println("Register yourself first!!!");
            }}
            else{
                System.out.println("You cannot comment about yourself!!!");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        home obj=new home();
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
