/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personality;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import org.python.core.PyObject;
import org.python.util.PythonInterpreter;
/**
 *
 * @author MOHIT
 */
public class comment extends javax.swing.JFrame {

    /**
     * Creates new form comment
     */
    public comment() {
        initComponents();
        setBounds(450, 180, 350, 400);
        getContentPane().setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 180, 350, 400));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Your Roll No.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 100, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Roll No.");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 100, 49, 17);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 60, 140, 23);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 100, 140, 23);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 350, 85, 25);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personality/11.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 10, 32, 32);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personality/1.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 10, 32, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("(Person to be commented on)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 120, 140, 13);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Comment Below:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 200, 110, 17);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 220, 250, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personality/5.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 130, 111, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/per?autoconnect=true&useSSl=false","root","");
            Statement stmt=con.createStatement();
            long roll=Long.parseLong(jTextField1.getText());
            long roll1=Long.parseLong(jTextField2.getText());
            long sd=0,rd=0;
            String s2="",n1="",n2="";
            int pt=0;
            if(roll!=roll1){
            ResultSet rs=stmt.executeQuery("SELECT * FROM main WHERE roll='"+roll+"'");
            while(rs.next()){
                sd=Long.parseLong(rs.getString("aadhar"));
                System.out.println(sd);
                s2=rs.getString("email");
                n2=rs.getString("name");
            }
            ResultSet rs1=stmt.executeQuery("SELECT * FROM main WHERE roll='"+roll1+"'");
            while(rs1.next()){
                rd=Long.parseLong(rs1.getString("aadhar"));
                System.out.println(rd);
            }
            if(sd!=0 && rd!=0){
                Properties properties = System.getProperties();
	PythonInterpreter.initialize(properties, properties, new String[0]);
	PythonInterpreter interp = new PythonInterpreter();
        String x=jTextArea1.getText();
	interp.exec("import sys\n" +"sys.argv = ['"+x+"']");
	interp.execfile("E:\\personality\\src\\personality\\newfile1.py");
        PyObject xy=interp.get("x"); 
       System.out.print(xy);
       //pt=Integer.parseInt(xy.toString());
       pt=2;
            double t=0.0,p=0.0;
            String s="";
            String sql="INSERT INTO comment (saadhar, raadhar, points)VALUES ('"+sd+"', '"+rd+"','"+pt+"')";
            stmt.executeUpdate(sql);
            ResultSet rs2=stmt.executeQuery("SELECT * FROM main WHERE roll='"+roll1+"'");
            while(rs2.next()){
                t=Double.parseDouble(rs2.getString("total"));
                p=Double.parseDouble(rs2.getString("points"));
                s=rs2.getString("email");
                n1=rs2.getString("name");
            }
            t+=1;
            if(pt>0){
                p+=1;
            }
            if(pt==0){
                p+=0.5;
            }
            stmt.executeUpdate("UPDATE main SET total='"+t+"' WHERE roll='"+roll1+"'");
            stmt.executeUpdate("UPDATE main SET points='"+p+"' WHERE roll='"+roll1+"'");
             System.out.println("updated");
              System.out.println("Sending Mail....");
              
        SendMail obj=new SendMail();
        obj.send(s,"New Comment","Someone has added a new comment. Now your scores are "+p+"/"+t+". Thank You!","npp95239@gmail.com","17309521913");     
          obj.send(s2,"Added New Comment","Hi '"+n2+"'! You just have commented about '"+n1+"'. Thank You for commenting!","npp95239@gmail.com","17309521913");
            jTextField1.setText("");
        jTextField2.setText("");
       jTextArea1.setText("");
            }
            else{
                System.out.println("Register yourself first!!!");
            }}
            else{
                System.out.println("You cannot comment about yourself!!!");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        home obj=new home();
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
